# Rubik's Cube Video Solver

In [92]:
import ipykernel
import json
import os

# Get the connection file path
connection_file_path = ipykernel.get_connection_file()

# Read the connection file to get kernel details
with open(connection_file_path) as f:
    connection_info = json.load(f)

# The 'argv' key in connection_info typically contains the path to the kernel executable
# For Python kernels, this usually points to the Python interpreter being used by the kernel.
print(connection_info)
# kernel_executable_path = connection_info['argv'][0]

# print(f"Connection File Path: {connection_file_path}")
# print(f"Kernel Executable Path: {kernel_executable_path}")

# # You can also get the directory where the kernel's connection file is located
# kernel_runtime_dir = os.path.dirname(connection_file_path)
# print(f"Kernel Runtime Directory: {kernel_runtime_dir}")

{'key': 'e529e152-6017-4a65-b80d-b9ca47dd97c5', 'signature_scheme': 'hmac-sha256', 'transport': 'tcp', 'ip': '127.0.0.1', 'hb_port': 9005, 'control_port': 9006, 'shell_port': 9007, 'stdin_port': 9008, 'iopub_port': 9009, 'kernel_name': 'python396jvsc74a57bd01010f2fc08f6b6edd8bf08d663ce21e8708012106a03165dc8af694ad60979d1'}


In [3]:
%pip install rubik_solver

  Using cached rubik_solver-0.2.0.tar.gz (3.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached future-0.16.0.tar.gz (824 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for rubik_solver: filename=rubik_solver-0.2.0-py3-none-any.whl size=3684040 sha256=ee1991bbbf219e0ef172192fb1ab8e964ecec7523d0034d1f141736185751900
  Stored in directory: /Users/jack/Library/Caches/pip/wheels/e6/b9/dc/34f7b5945c8b4ab9c1cd778c40b1b74a75765584653497ec36
  Created wheel for future: filename=future-0.16.0-py3-none-any.whl size=487874 sha256=3d24c0c9a362f6962ca09bfc3d2a2ff1016b81421768f817450977691e1c6cde
  Stored in directory: /Users/jack/Library/Caches/pip/wheels/6e/bc/19/ea1496b17b60d45b1503dfb87704b1246bfaca822ce9880fd9
Successfully built rubik_solver future
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [93]:
from rubik_solver import utils
cube = 'wowgybwyogygybyoggrowbrgywrborwggybrbwororbwborgowryby'
print(len(cube))
utils.solve(cube, 'Kociemba')

54


[L', F, B2, R', B, R', L, B, D', F', U, B2, U, F2, D', R2, L2, U, F2, D']

In [3]:
%pip install opencv-python Pillow

  Using cached opencv_python-4.11.0.86-cp37-abi3-macosx_13_0_arm64.whl.metadata (20 kB)
Using cached opencv_python-4.11.0.86-cp37-abi3-macosx_13_0_arm64.whl (37.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 31.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 73.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [opencv-python]0m [opencv-python]
Note: you may need to restart the kernel to use updated packages.


In [94]:
a = ['b', 'cd', 'aaa']
sum(a)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [82]:
import numpy as np
import cv2 
file_name = 'test_vids/test_im.jpg'

img = cv2.imread(file_name)
# resize
# img = cv2.resize(img, (0, 0), fx = 0.1, fy = 0.1)
# img = cv2.resize(img, (0, 0), fx = 0.15, fy = 0.15)
# img = cv2.resize(img, (0, 0), fx = 0.2, fy = 0.2)
# gray scaled
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

## canny edge
edges = cv2.Canny(gray, 100, 200)

## contours
# contours, hierarchy = cv2.findContours(edges,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
# contour_threshold = 150
# big_contours = [i for i in range(len(contours)) if len(contours[i]) > contour_threshold]
# for i in big_contours:
#     cv2.drawContours(img, contours, i, (0, 0, 255), 3)
# cv2.namedWindow('Contours',cv2.WINDOW_NORMAL)
# cv2.imshow('Contours', img)

## corner detection
# gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# edges = cv2.Canny(gray, 50, 150)
# gray = np.float32(gray)
# dst = cv2.cornerHarris(gray,2,5,0.07)
# img[dst>0.01*dst.max()]=[0,0,255]
# dst = cv2.dilate(dst, None)

# line segment detector
lsd = cv2.createLineSegmentDetector(0)
line_segments = lsd.detect(gray)[0] # Position 0 of the returned tuple are the detected lines
edges = lsd.drawSegments(np.zeros(img.shape, dtype=np.int8), line_segments)
edges = np.float32(edges)
edges = cv2.cvtColor(edges,cv2.COLOR_BGR2GRAY)
edges = np.uint8(edges)


lines = cv2.HoughLines(edges,1,np.pi/180,200)
for line in lines:
    rho,theta = line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*rho
    y0 = b*rho
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))
    cv2.line(img,(x1,y1),(x2,y2),(0,0,255),2)

# lines = cv2.HoughLinesP(edges,1,np.pi/180,200,minLineLength=50,maxLineGap=10)
# for line in lines:
#     x1,y1,x2,y2 = line[0]
#     cv2.line(img,(x1,y1),(x2,y2),(0,0,255),2)

print(lines)

cv2.namedWindow('Image', cv2.WINDOW_NORMAL)
# cv2.namedWindow('Gray', cv2.WINDOW_NORMAL)
# cv2.namedWindow('Edges', cv2.WINDOW_NORMAL)
cv2.imshow('Image', img)
# cv2.imshow('Gray', gray)
# cv2.imshow('Edges', edges)
if cv2.waitKey(0):
    cv2.destroyAllWindows()
cv2.waitKey(0)
cv2.destroyAllWindows()
# # and finally destroy/close all open windows

[[[-7.8100000e+02  3.1241393e+00]]

 [[ 1.1060000e+03  0.0000000e+00]]

 [[ 1.6880000e+03  3.4906585e-02]]

 [[ 1.1280000e+03  1.7453292e-02]]

 [[ 7.7500000e+02  0.0000000e+00]]

 [[-7.3600000e+02  3.0892327e+00]]

 [[ 1.3850000e+03  1.7453292e-02]]

 [[-5.1500000e+02  3.1241393e+00]]

 [[ 1.3830000e+03  1.1868238e+00]]

 [[ 8.9200000e+02  2.0071287e+00]]

 [[ 1.0570000e+03  0.0000000e+00]]

 [[ 1.7290000e+03  3.4906585e-02]]

 [[ 5.6700000e+02  1.2740903e+00]]

 [[ 5.6200000e+02  1.9547688e+00]]

 [[ 2.1900000e+02  1.9373155e+00]]

 [[ 5.9100000e+02  1.9722221e+00]]

 [[ 5.9000000e+01  1.9198622e+00]]

 [[-1.0290000e+03  3.1241393e+00]]

 [[ 1.6700000e+03  1.7453292e-02]]

 [[ 1.7690000e+03  1.1519173e+00]]

 [[ 1.4580000e+03  1.1519173e+00]]

 [[ 1.0040000e+03  1.2391838e+00]]

 [[ 5.8000000e+02  1.2566371e+00]]

 [[-7.9000000e+02  3.1241393e+00]]

 [[ 1.8060000e+03  1.1519173e+00]]

 [[ 8.6900000e+02  1.9896753e+00]]

 [[ 5.4700000e+02  1.9722221e+00]]

 [[ 1.3900000e+03  1.7453292